### ISSUE TITLE
色変記事推薦(他薦)

### ISSUE THREAD

**Issue by ansainbdg** [KATO-Hiro/AtCoderClans#1663]
## 優先度: 中

- [x] サービス・ツール名:AtCoder黄色になるまでにやったこととやっていないこと
  - URL:https://ks2m.hatenablog.com/entry/2021/03/08/230503
  - ユーザー:https://atcoder.jp/users/ks2m
  - 概要:結構な大作だけど界隈にいないからか知名度低すぎるので推薦

**Comment by KATO-Hiro** [comment]
@ansainbdgさん

ご紹介いただき、ありがとうございます。

記事を拝見した上で、掲載させていただきたいと思います。
