### ISSUE TITLE
mediaページへの記事の追記及び修正です。

### ISSUE THREAD

**Issue by daikisuyama** [KATO-Hiro/AtCoderClans#2641]
# 追記

- [x] 記事名:Pythonで競プロするのに必要な機能をまとめてみた\~itertools\~
  - URL:https://qiita.com/DaikiSuyama/items/11f63a94d63fa72e8bf4
  - 概要:Pythonのitertoolsライブラリを競技プログラミングで使う方法をドキュメント形式でまとめた記事。使用方法だけでなく使用可能な問題も載せている。

- [x] 記事名: MacでGCCを"正しく"環境構築しよう！
  - URL:https://qiita.com/DaikiSuyama/items/09f5aa399aad37783146
  - 概要:MacでのGCCの環境構築を解説した記事。パッケージ管理システムであるHomebrewを用いたGCCのインストールから設定までを解説している。
 
- [x] 記事名: 競プロの応用事項確認\~ランレングス圧縮\~
  - URL:https://qiita.com/DaikiSuyama/items/07e237b7372e7c7b3432
  - 概要:競技プログラミングにおけるランレングス圧縮の利用方法をPythonを用いて解説した記事。

# 修正

- [x] 記事名:bits/stdc++.hのインクルードを高速化しよう！
  - URL:https://qiita.com/DaikiSuyama/items/e502e09a1090f4a2cee3
  - 概要:GCCのヘッダファイルであるbits/stdc++.hを正しく使うことで、コンパイルを高速化する方法を紹介した記事。
  - 修正希望
    - 理由：記事内容を一部変更したため
    - 希望内容1：特定のOSに依存しない内容→Macintoshへの移動
    - 希望内容2：概要を上記へと変更

**Comment by KATO-Hiro** [comment]
@daikisuyamaさん

記事の修正リクエストおよび新たな記事をご紹介いただき、ありがとうございます。

対応させていただきたいと思います。

**Comment by KATO-Hiro** [comment]
@daikisuyamaさん

## 記事を拝見した感想

itertoolsモジュールのgropuby関数の解説やランレングス圧縮を応用する視点が特に印象に残りました。ご紹介いただき、ありがとうございます。

## 対応状況

ご提示いただいた全ての記事の追加・修正を行いました。

- 1番目と3番目の記事: [コードを実装するときの工夫 - Python](https://kato-hiro.github.io/AtCoderClans/media#python-1)に掲載しました。

- 2番目の記事: [コードを快適に書くための環境構築 - Macintosh](https://kato-hiro.github.io/AtCoderClans/media#macintosh)に掲載しました。

- 4番目の記事: ご提案いただいた内容をそのまま反映しました。

なお、1〜3番目の記事の説明文につきましては、ご提示いただいだ内容をベースに、一部加筆・修正しました。ご了承ください。

ご多用のところ大変恐縮ですが、ご確認いただいてもよろしいでしょうか?

**Comment by daikisuyama** [comment]
記事の説明文等について問題がないことを確認いたしました。
陰ながらこれからもAtCoder Clansを応援しております。

**Comment by KATO-Hiro** [comment]
@daikisuyamaさん

ご確認いただき、ありがとうございます。

今後ともよろしくお願いいたします。
