### ISSUE TITLE
compro-categoryを追加

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderClans#438]
https://github.com/ningenMe/compro-category-front

**Comment by KATO-Hiro** [comment]
ログインができない?
自分が確認できていないだけ?

**Comment by ningenMe** [comment]
こんにちは。
こちら自分(ningenMe)しかユーザを作れない趣味用となっています。clansに載せる感じじゃないです。悪しからず......。

**Comment by KATO-Hiro** [comment]
@ningenMeさん

こんばんは。
教えていただき、ありがとうございます。
