### ISSUE TITLE
コマンドラインツールの分類基準がおかしい

### ISSUE THREAD

**Issue by kmyk** [KATO-Hiro/AtCoderClans#466]
「ローカル環境でサンプルのテストを実行する」の中の分類は以下のようになっています。これを対応言語ごとの分類にしてほしいです。

> 類似した機能を持つツールが多いため、実装されている言語別に分類しています。

---

ツールを探すときにその実装言語を見たいユーザは少ないはずです。
上位の分類が「複数のファイルを一つにまとめるツール」「問題の作成と準備を支援するツール」などの (実装言語でなく) 用途ごとの分類になっているのと同様に、ここも実装言語でなく対応言語ごとの分類だとうれしい気がします。
また、たとえば「Common Lisp で書かれた任意の言語のプログラムを実行できるツール (例: [fukamachi/getac](https://github.com/fukamachi/getac))」「Rust で書かれた Rust 専用のツール (例: [shino16/cargo-auto-bundle](https://github.com/shino16/cargo-auto-bundle)) 」「Python で書かれた C++ コードを生成するツール (例: [online-judge-tools/template-generator](https://github.com/online-judge-tools/template-generator))」などがあるように、実装言語と対応言語は基本的に無関係です。

**Comment by KATO-Hiro** [comment]
ご指摘いただき、ありがとうございます。

おっしゃる通りだと思います。

修正いたします。

**Comment by KATO-Hiro** [comment]
@kmykさん

テストツールを対応言語別に分類しました。

お手すきの際に、ご確認いただけますでしょうか?

**Comment by kmyk** [comment]
ありがとうございます。よさそうです。

issue は閉じておきますね。

**Comment by KATO-Hiro** [comment]
ご確認いただき、ありがとうございます。
