### ISSUE TITLE
乗ってない重要サービス・ツール一覧

### ISSUE THREAD

**Issue by kmyk** [KATO-Hiro/AtCoderClans#489]
「これが漏れてるのはまずいだろ」って感じのものを列挙しておきます。
たくさんあるので issue template は無視してひとつの issue でまとめて置いておきます。既に書かれているツールや方針的に書かないツールについては無視してください。
このあたりがきちんと全部乗ってるとより便利なのでよろしくお願いします。

## 重要なツール

- https://clist.by/
  - ほぼすべてのコンテストのカレンダー情報がまとまってるサイト
- https://github.com/icpc-jag/rime
  - 少なくとも日本では、作問用ツールというとこれ一択
- https://github.com/nodchip/OnlineJudgeHelper
  - サンプルをテストしてくれるツール。この手のツールの中で日本で最初のもの。いまでもメンテされてるかは不明だけど歴史的に重要
- https://github.com/jmerle/competitive-companion
  - サンプルを取得してくれる (取得するだけ) ブラウザ拡張
  - その結果を受けとってテストに使ってくれる IDE プラグインがたくさんある
    - https://plugins.jetbrains.com/plugin/7091-chelper https://plugins.jetbrains.com/plugin/7541-jhelper あたりは有名
  - 同じフォーマットでサンプルケースを出力してくれるツールは他にもある
       - 例: https://github.com/online-judge-tools/api-client

## おまけ: AtCoder には対応してないが重要なツール

- https://github.com/dj3500/hightail
  - サンプルをテストしてくれるツール (GUI)。Codeforces 専用ぽいけどとても古くからあって歴史的に重要
- https://github.com/xalanq/cf-tool
  - サンプルをテストしてくれるツール。Codeforces 専用だけどユーザ数は非常に多い
- https://github.com/zen0wu/topcoder-greed
   - Topcoder の Java arena のプラグイン。入出力フォーマットに沿ったテンプレートコードを生成してくれたり、サンプルテストができるようにしてくれたりする。ユーザ数が多い

## おまけ: 重要度は一段落ちるがおもしろいツール

- https://github.com/nejiko96/at_coder_friends
  - サンプルをテストしてくれるツール。atcoder-tools などと同様に、入力フォーマットを解析してのテンプレートコード生成機能もある
- https://github.com/online-judge-tools/verification-helper
  - ライブラリのテストを自動化するツール。C++ のファイルをひとつにまとめて提出できるようにする機能なども含む
- https://github.com/fukatani/rujaion
  - 競プロ用の IDE
- https://github.com/qryxip/snowchains
  - サンプルをテストしてくれるツール。takoha-cpp/WrongAnswer などと同様に、AtCoder のシステムテストのケースの取得機能もある

**Comment by KATO-Hiro** [comment]
多くのツールをご紹介いただき、ありがとうございます。

「重要なツール」から優先的に掲載したいと思います。

**Comment by KATO-Hiro** [comment]
途中経過の報告です。

下記のWebサイトおよびツールを追加しました。ご紹介いただいたツールについて、順次追加する予定です。

> ## 重要なツール
> * https://clist.by/
>   * ほぼすべてのコンテストのカレンダー情報がまとまってるサイト

> * https://github.com/icpc-jag/rime
>   * 少なくとも日本では、作問用ツールというとこれ一択

> * https://github.com/nodchip/OnlineJudgeHelper
>   * サンプルをテストしてくれるツール。この手のツールの中で日本で最初のもの。いまでもメンテされてるかは不明だけど歴史的に重要

**Comment by KATO-Hiro** [comment]
@kmykさん

ご紹介いただいたツールを確認した上で、全て掲載しました。

お手すきの際に、ご確認いただいてもよろしいでしょうか?


多くのツールは、Commnad line toolsに該当すると思いますが、よりふさわしいカテゴリがあると判断したものについては、以下のページに掲載しています。

> ## 重要なツール
> * https://clist.by/
>   * ほぼすべてのコンテストのカレンダー情報がまとまってるサイト

+ https://kato-hiro.github.io/AtCoderClans/web_app#%E3%82%B3%E3%83%B3%E3%83%86%E3%82%B9%E3%83%88%E3%81%AE%E9%96%8B%E5%82%AC%E4%BA%88%E5%AE%9A%E3%82%92%E7%A2%BA%E8%AA%8D%E3%81%99%E3%82%8B%E7%99%BB%E9%8C%B2%E3%81%99%E3%82%8B

> * https://github.com/jmerle/competitive-companion
>   * サンプルを取得してくれる (取得するだけ) ブラウザ拡張
>   * その結果を受けとってテストに使ってくれる IDE プラグインがたくさんある
>     
>     * https://plugins.jetbrains.com/plugin/7091-chelper https://plugins.jetbrains.com/plugin/7541-jhelper あたりは有名

+ https://kato-hiro.github.io/AtCoderClans/scripts#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%82%B1%E3%83%BC%E3%82%B9%E3%81%AE%E5%8F%96%E5%BE%97

> ## おまけ: AtCoder には対応してないが重要なツール

+ ツールの性質を踏まえ、AtCoderをサポートの対象外としていることを明記し、新たにページを作成しました。
+ https://kato-hiro.github.io/AtCoderClans/related_contest_sites


> ## おまけ: 重要度は一段落ちるがおもしろいツール
> * https://github.com/online-judge-tools/verification-helper
>   
>   * ライブラリのテストを自動化するツール。C++ のファイルをひとつにまとめて提出できるようにする機能なども含む

+ Library Checker Problemsとの関係性からライブラリのページにあった方がよいと判断しました。
+ https://kato-hiro.github.io/AtCoderClans/libraries#%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%83%81%E3%82%A7%E3%83%83%E3%82%AB%E3%83%BC

> * https://github.com/fukatani/rujaion
>   
>   * 競プロ用の IDE

+ 該当する分類のツールが少ないため、暫定的な配置です。
+ https://kato-hiro.github.io/AtCoderClans/web_app#ide

**Comment by kmyk** [comment]
@KATO-Hiro 確認しました。よさそうです。丁寧な対応ありがとうございます

**Comment by KATO-Hiro** [comment]
@kmykさん

ご確認いただき、ありがとうございます。

今後とも、よろしくお願いいたします。
