### ISSUE TITLE
自作ツールの紹介

### ISSUE THREAD

**Issue by naskya** [KATO-Hiro/AtCoderClans#511]
# サービス、ツールなどの名称(必須)

+ testcase-generator

## 概要(必須)

+ 競技プログラミングで使える、テストケース生成ツールを作ってみました。使用方法が少し複雑ですが、大量にテストケースを生成して WA になってしまった解と愚直解とを比較することなどもできるので役に立つと思います。

## サービス、ツールのURL(必須)

+ https://github.com/naskya/testcase-generator

## 区分、分類(必須)

+ コマンドラインツール

## GitHubレポジトリのURL(任意)

+ https://github.com/naskya/testcase-generator (上と同じ)

**Comment by KATO-Hiro** [comment]
ツールをご紹介いただき、ありがとうございます。

掲載させていただきたいと思います。

**Comment by KATO-Hiro** [comment]
@naskya さん

掲載いたしました。

紹介文と画像について、ご確認いただけますでしょうか?

https://kato-hiro.github.io/AtCoderClans/cli#%E3%83%86%E3%82%B9%E3%83%88%E3%82%B1%E3%83%BC%E3%82%B9%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B%E3%83%84%E3%83%BC%E3%83%AB

**Comment by naskya** [comment]
@KATO-Hiro さん
ありがとうございます。せっかく説明を書いていただいて申し訳ないのですが、

> 生成できる整数・文字列は、利用している環境下でのC++のlong long型、char型(一部の文字を除く)で扱えるものが対象である。

この一文は紹介文に含めるほどの内容ではないと思うので削除していただけるとより見やすくなると思います。
(この文は「10^18 くらいの大きい数も生成できるけど、10^100 みたいな非常に大きい数は生成できないよ」ということを説明する注意書きのようなもので、実際に私のリポジトリまで訪れた人が確認できさえすれば良い情報かなと思っています。)

その他の点については全く問題ありません。

**Comment by KATO-Hiro** [comment]
@naskya さん

ご確認いただき、ありがとうございます。

> > 生成できる整数・文字列は、利用している環境下でのC++のlong long型、char型(一部の文字を除く)で扱えるものが対象である。
> 
> この一文は紹介文に含めるほどの内容ではないと思うので削除していただけるとより見やすくなると思います。

承知いたしました。該当部分を削除いたします。

**Comment by naskya** [comment]
度々すみません！

[testcase-generator](https://github.com/naskya/testcase-generator) を更新した（というか完全に書き直して別物にした）結果、表示される画面が大分変わったので今サイトに掲載されている gif 動画の部分は削除していただけますでしょうか。

**Comment by KATO-Hiro** [comment]
@naskyaさん

gifアニメーションまで作成していただき、ありがとうございます。

是非とも、掲載させてください。
