### ISSUE TITLE
「Misskey」と「Misskey.io」を混同している

### ISSUE THREAD

**Issue by strangerxxxx** [KATO-Hiro/AtCoderClans#7450]
`Misskey`はSNS名、`Misskey.io`はMisskeyのサーバーの1つであり、[SNSページ](https://kato-hiro.github.io/AtCoderClans/sns/)では混同されているようなので訂正しておきます。
`競プロ鯖`も数あるMisskeyサーバーの1つです。ですからMisskey.ioとは異なります。紛らわしいですね。

なお`Misskey.io`の方には競プロチャンネルがあるので紹介しておきます。
https://misskey.io/channels/9b1va5xjkr

**Comment by KATO-Hiro** [comment]
教えていただき、ありがとうございます。
修正・加筆させていただきたいと思います。

**Comment by strangerxxxx** [comment]
ありがとうございます！ただMisskey競プロ部の運営は私ではない(誰か把握できていないのですが)ので、時間があるときに訂正しておいてください。

**Comment by KATO-Hiro** [comment]
ご確認いただき、ありがとうございます！
修正いたします。
