### ISSUE TITLE
「Atcoder Companion」を追加

### ISSUE THREAD

**Issue by conlacda** [KATO-Hiro/AtCoderClans#8564]
## 優先度: 中

- サービス・ツール名: Atcoder Companion
- URL: https://chromewebstore.google.com/detail/atcoder-companion/bflhekmjlbpdlibcmojpikplaldgceec
- 概要: こちらの拡張機能を使用すると、テスト ケース全体をダウンロードしてコピーしたり、提出された結果を表示したり、コンテストでのパフォーマンスや評価を予測したりできます。

**Comment by KATO-Hiro** [comment]
便利なツールをご紹介いただき、ありがとうございます。
掲載させていただきたいと思います。
