### ISSUE TITLE
Webサービス「AtCoder Graphs β」を追加

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderClans#9086]
https://atcoder-graphs.vercel.app/

https://x.com/kiri8128/status/1846558546399556048

**Comment by yunix-kyopro** [comment]
いつもお世話になっております。
https://kato-hiro.github.io/AtCoderClans/web_app/view_and_compare_scores/
こちらに記載いただいている、AtCoder Rating Contributor Graphはkiriさんが開発されたものをyunixがホスティングするサイトを立てたものです。
上記のkiriさんがご自身でホスティングされるようになったので、上記のページからAtCoder Rating Contributor Graphの記述を削除する、または上記のURLのものに貼り替えていただければと思います。重複したサイトを置いておくのもあれなので、AtCoder Clansさんの記載が切り替わり次第、元のサイトは閉じようと思っています。

お手数ですがよろしくお願いいたします。

**Comment by KATO-Hiro** [comment]
いつもお世話になっております。
教えていただき、ありがとうございます。

元のサイトを閉鎖される予定があることについて、承知いたしました。
これまでサイトの開発およびホスティングをしていただき、ありがとうございました。

「AtCoder Graphs β」の掲載に併せて、「AtCoder Rating Contributor Graph」をArchivesページに移動させようと考えています。

よろしくお願いいたします。
