### ISSUE TITLE
naminodarie/SourceExpander の説明文について

### ISSUE THREAD

**Issue by naminodarie** [KATO-Hiro/AtCoderClans#929]
## 優先度: 高

https://kato-hiro.github.io/AtCoderClans/libraries#acl-c-2 にて

> naminodarie/SourceExpander GitHub Repo stars - key-moon/ac-library-csを利用したコードをジャッジシステムに提出できる形式に変換するライブラリ。

とありますが、当該ライブラリを利用するためのコードはマージされていないので key-moon/ac-library-cs のコードは変換できません。

naminodarie/ac-library-csharp にて対応しています。

- [x] naminodarie/ac-library-csharp
  - URL: https://github.com/naminodarie/ac-library-csharp
  - 概要: key-moon/ac-library-cs のFork。ソースコード埋め込み機能、C++ STLの移植、ac-libraryの最新版への追従対応を行っている。

**Comment by KATO-Hiro** [comment]
@naminodarieさん

ご指摘いただき、ありがとうございます。

該当箇所の修正を試みるとともに、ご紹介いただいたライブラリを追記しました。
